### ISSUE TITLE
No more `updated` and `title` fields in the generated JSON

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/gsheets#9]
Upgraded from gsheets 1.x to 3.x and the tool no longer includes the two fields `updated` and `title` in the generated JSON. Is that due to a change in the Google Sheets API? Can we get the fields back?

**Comment by jstcki** [comment]
If I understood @ovbm correctly, these are now missing from the API. But if you find them, it would be great to have them back 😉

**Comment by ovbm** [comment]
unfortunately the api doesn't return those fields anymore.

**Comment by wereHamster** [comment]
Ok. I'll have to see if my project really requires those, or if we can work around this. Thanks.
